### ISSUE TITLE
Kinematics-test failed

### ISSUE THREAD

**Issue by TsuruMasato** [mehdi-benallegue/state-observation#10]
`1 -0.659789 -0.659789 0.642074 0.642074 1.11022e-16 0`
`Test number 0isRotationTest failed: false negative`
`testRotationOperations Failed, error code: 1`

As shown above, the kinematics test failed.
I met this problem when I was running an install script of mc_rtc.
This issue stopped the installation process, so I disabled this test from cmake option.

Other tests finished correctly.

It's just a small report, in case.

**Comment by mehdi-benallegue** [comment]
Thank you for this issue, but can you please use at the main repository at this link? 
**https://github.com/jrl-umi3218/state-observation**

If you meet the same problem please open an issue there.

**Comment by TsuruMasato** [comment]
Oh, it worked on the main repository! Thank you!
